from django.db import models

# Create your models here.
class International(models.Model):
    fio = models.CharField(max_length=255, null=True, blank=True)
    region = models.CharField(max_length=255, null=True, blank=True)
    iin = models.CharField(max_length=255, null=True, blank=True)
    report_date = models.CharField(max_length=255, null=True, blank=True)
    report_time = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    oferta = models.CharField(max_length=255, null=True, blank=True)
    tests = models.CharField(max_length=255, null=True, blank=True)
    payment_check = models.FileField(upload_to='media/files', null=True, blank=True)
    number = models.CharField(max_length=20, null=True, blank=True)
    udostoverenie = models.FileField(upload_to='media/files', null=True, blank=True)
    sex = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    created_date = models.DateTimeField(auto_now=True)

class Student(models.Model):
    fio = models.CharField(max_length=255, null=True, blank=True)
    region = models.CharField(max_length=255, null=True, blank=True)
    iin = models.CharField(max_length=255, null=True, blank=True)
    report_date = models.CharField(max_length=255, null=True, blank=True)
    report_time = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    oferta = models.CharField(max_length=255, null=True, blank=True)
    tests = models.CharField(max_length=255, null=True, blank=True)
    payment_check = models.FileField(upload_to='media/files', null=True, blank=True)
    number = models.CharField(max_length=20, null=True, blank=True)
    udostoverenie = models.FileField(upload_to='media/files', null=True, blank=True)
    sex = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    created_date = models.DateTimeField(auto_now=True)

class Courses(models.Model):
    fio = models.CharField(max_length=255, null=True, blank=True)
    region = models.CharField(max_length=255, null=True, blank=True)
    iin = models.CharField(max_length=255, null=True, blank=True)
    report_date = models.CharField(max_length=255, null=True, blank=True)
    report_time = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    oferta = models.CharField(max_length=255, null=True, blank=True)
    tests = models.CharField(max_length=255, null=True, blank=True)
    payment_check = models.FileField(upload_to='media/files', null=True, blank=True)
    number = models.CharField(max_length=20, null=True, blank=True)
    udostoverenie = models.FileField(upload_to='media/files', null=True, blank=True)
    sex = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    created_date = models.DateTimeField(auto_now=True)