# Generated by Django 4.1.4 on 2022-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_rename_text_post_desc_rename_name_post_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=55, null=True)),
                ("author", models.CharField(blank=True, max_length=55, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="pics"),
        ),
    ]
