# Generated by Django 4.1.1 on 2022-12-14 09:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
