# Generated by Django 4.1.4 on 2022-12-13 10:42

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_comment_alter_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="desc",
            field=django_quill.fields.QuillField(default="1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="desc",
            field=django_quill.fields.QuillField(default="1"),
            preserve_default=False,
        ),
    ]
