# Generated by Django 4.1.4 on 2022-12-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_post_about_alter_article_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="artticle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.article",
            ),
        ),
    ]
