# Generated by Django 4.1.4 on 2022-12-27 09:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_comment_artticle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Категорий"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарий",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(
                blank=True, max_length=55, null=True, verbose_name="Автор"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="desc",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                blank=True, max_length=55, null=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Под заголовок"),
        ),
        migrations.AlterField(
            model_name="post",
            name="cat_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="news.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="desc",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Текст"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="pics", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Заголовок"
            ),
        ),
    ]
