# Generated by Django 4.1.1 on 2022-12-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
    ]
