# Generated by Django 4.1.4 on 2022-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_article_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
