# Generated by Django 4.1.4 on 2023-01-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("iin", models.CharField(max_length=255)),
                ("report_date", models.DateField()),
                ("report_time", models.TimeField()),
                ("email", models.EmailField(max_length=255)),
                ("oferta", models.CharField(max_length=255)),
                ("tests", models.CharField(max_length=255)),
                ("payment_check", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=20)),
                ("udostoverenie", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("created_date", models.DateTimeField()),
            ],
        ),
    ]
