# Generated by Django 4.1.4 on 2023-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urequest", "0002_alter_urequest_payment_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urequest",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="fio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="iin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="oferta",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="report_date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="report_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="sex",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="urequest",
            name="tests",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
