# Generated by Django 4.1.4 on 2023-01-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "urequest",
            "0003_alter_urequest_country_alter_urequest_created_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="International",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("iin", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "report_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "report_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("oferta", models.CharField(blank=True, max_length=255, null=True)),
                ("tests", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_check",
                    models.FileField(blank=True, null=True, upload_to="media/files"),
                ),
                ("number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "udostoverenie",
                    models.FileField(blank=True, null=True, upload_to="media/files"),
                ),
                ("sex", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("iin", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "report_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "report_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("oferta", models.CharField(blank=True, max_length=255, null=True)),
                ("tests", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_check",
                    models.FileField(blank=True, null=True, upload_to="media/files"),
                ),
                ("number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "udostoverenie",
                    models.FileField(blank=True, null=True, upload_to="media/files"),
                ),
                ("sex", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="URequest",
            new_name="Courses",
        ),
    ]
