# Generated by Django 4.1.1 on 2022-12-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTypeThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_location', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=255)),
                ('adres', models.CharField(max_length=255)),
                ('lgota', models.CharField(max_length=255)),
                ('dokument', models.FileField(blank=True, null=True, upload_to='files')),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
