# Generated by Django 4.1.4 on 2022-12-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requestapp", "0002_alter_request_ustav_copy"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestTypeTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_location", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("father_name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=255)),
                ("adres", models.CharField(max_length=255)),
                ("cvalification", models.CharField(max_length=255)),
                (
                    "udostoverenie",
                    models.FileField(blank=True, null=True, upload_to="files"),
                ),
                ("diplom", models.FileField(blank=True, null=True, upload_to="files")),
                (
                    "udostoverenie_category",
                    models.FileField(blank=True, null=True, upload_to="files"),
                ),
                (
                    "dok_staj",
                    models.FileField(blank=True, null=True, upload_to="files"),
                ),
                ("comment", models.CharField(max_length=255)),
                (
                    "prolojenie",
                    models.FileField(blank=True, null=True, upload_to="files"),
                ),
            ],
        ),
    ]
